### ISSUE TITLE
TO DO LIST/BUG FIXES

### ISSUE THREAD

**Issue by jeremyleung521** [jeremyleung521/molecool#5]
To do List/Bug Fixes for Github issue/pull request templates:

- [x] A Code of Conduct link on the right (Helpful resources)  CODE_OF_CONDUCT.md in .github.
  - Copied from Wiki
- [x] A Contributing link (CONTRIBUTING.md in .github)
  - Copied from Wiki
- [x] AUTHOR page on WESTPA is not in alphabetical order
- [x] Bug issues template
- [x] Feature request issues template
- [x] Issues YAML file
- [x] Pull Request template file

All checked things are ready to go in my fork branch: jeremyleung521/westpa2-pull_templates

**Comment by darianyang** [comment]
Looks good!
